name: Automation test on ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn clean install
        # or "mvn clean test" if you only want tests without install

      #
      # Archive Surefire test reports
      #
      - name: Archive Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      #
      # Archive Extent Reports (adjust the path if your Extent reports go elsewhere)
      #
      - name: Archive Extent Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: reports/ExtentReports

      #
      # Archive Allure Results
      #
      - name: Archive Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      #
      # (Optional) Generate Allure HTML Report and Archive It
      # Requires "io.qameta.allure:allure-maven" plugin configured in your pom.xml
      #
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Archive Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: target/site/allure-maven-plugin
